name             'sprout-osx-settings'
maintainer       'Ryan Baumbach'
maintainer_email 'rbaumbach.github@gmail.com'
license          'MIT'
description      'A fork of sprout-osx-settings from pivotal labs, Recipes to configure various aspects of OS X'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-base'
depends          'homebrew'
depends          'osx'
